### PR TITLE
do not give error for defaults in check protocol and experiment colum…

### PR DESCRIPTION
**Pull request by rvitancol**
…n inputs

do not give an error for defaults when checking for available columns in annotations for experiment and protocol data columns.

### CODE REVIEW

**Review by NicoleEO — CHANGES_REQUESTED** [review]
I'd rather keep the error as you had it and change the default readgeomxset params to be empty vectors. If these defaults aren't in the data inputs then they would just NA columns and these are not necessary defaults.

**Comment by rvitancol** [comment]
I agree. I will remove the defaults.

**Review by NicoleEO — CHANGES_REQUESTED** [review]
I think this now breaks section 156 with experimentList building. That section probably needs a check for experimentDataColNames not being null.

**Comment by rvitancol** [comment]
this should do it

**Pull request merged**
