### PR TITLE
Bioc3.19

### LINKED ISSUE #185: Handle older assay IDs
Please add the following

```r
  # Handle older assay probe labels
  if (pkcData[["RTS_ID"]][1] %like% "^RTS" &
    probeAssay[["RTS_ID"]][1] %like% "^RNA") {
    # replace RTS00 with RNA in probeAssay[["RTS_ID"]]
    probeAssay[["RTS_ID"]] <- gsub("^RNA", "RTS00", probeAssay[["RTS_ID"]])
  }
```
https://github.com/andrewrech/GeomxTools/commit/d567c3590cffc1afd8387e09d55a0a3942b33780

to handle assays that use the older probe labels.

thanks

Andrew

### LINKED ISSUE #190: Prepare for upcoming Seurat v5 release
I am opening this issue as a notification because `GeomxTools` is listed [here](https://cran.r-project.org/web/packages/Seurat/index.html) as a package that relies (depends/imports/suggests) on Seurat. As you may know, we recently released Seurat v5 as a beta in March of this year, with new updates for spatial, multimodal, and massively scalable analysis. For more information on updates and improvements, check out our website https://satijalab.org/seurat/.
We are now preparing to release Seurat v5 to CRAN, and plan to submit it on October 23rd. While we have tried our best to keep things backward-compatible, it is possible that updates to Seurat and SeuratObject might break your existing functionality or tests. We wanted to reach out before the new version is on CRAN, so that there's time to report issues/incompatibilities and prepare you for any changes in your code base that might be necessary.

We apologize for any disruption or inconvenience, but hope that the improvements to Seurat v5 will benefit your users going forward.
To test the upcoming release, you can install Seurat from the `seurat5` branch using the instructions available on this page: https://satijalab.org/seurat/articles/install.

Thank you!
Seurat v5 team

### LINKED ISSUE #191: Error coercing GeoMx data to Seurat object
Dear team,

I'm attempting to do a conversion between NanoStringGeoMxSet to a Seurat object using the GeoMxTools::as.Seurat() function. The relevant error is:
`Error in names(v) <- row.names(x = value) : 
  'names' attribute [179] must be the same length as the vector [1]`

I think I've worked through enough that I believe the issue stems from the Seurat::AddMetaData command. However, I've hit a dead end on the debug at this point.

Would greatly appreciate your support. Thanks!

Relevant environment:

R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
other attached packages:
[1] Seurat_4.9.9.9058       SeuratObject_5.0.0      sp_2.1-1                GeomxTools_3.2.0        NanoStringNCTools_1.6.1
[6] ggplot2_3.4.4           S4Vectors_0.36.2        Biobase_2.58.0          BiocGenerics_0.44.0

### PR DESCRIPTION
**Pull request by maddygriz**
- Seurat v5 coercions, resolves #190, resolves #191 
- improved proteogenomics error handling
- bug fix on area filtering
- old PKC compatibility, resolves #185 

devtools::check()
image
warning = qpdf 

R CMD build --keep-empty-dirs --no-resave-data GeomxTools & R CMD check
image
* checking PDF version of manual ... WARNING
* checking PDF version of manual without index ... ERROR

### CODE REVIEW

**Comment by maddygriz** [comment]
IPA test data can be found at HSDATA\SABonnett\GeoMx Tools\IPA Test

**Comment by NicoleEO** [comment]
@maddygriz there seems to be an issue with readPKC getting gene id from IPA pkc. Also, is there any chance to add RTSID to featureData as well?

**Comment by maddygriz** [comment]
@mgrout81 Dave H found an issue on this branch about pkc info not being added to the feature metadata correctly. I have addressed that issue. 
image

**Comment by mgrout81** [comment]
Thanks, I will update my package accordingly.

**Comment by mgrout81** [comment]
`readPKCFile()` appears to be working as expected. `NA` values above are in negative probes. 
image

**Comment by maddygriz** [comment]
Megan approved and completed PR

**Pull request merged**
