### PR TITLE
Update NanoStringGeoMxSet-normalize.R

### PR DESCRIPTION
**Pull request by johnyaku**
Fixed typo (capitalization)
Codeclass >> CodeClass in `subtractBackground()`

### CODE REVIEW

**Review by rvitancol — CHANGES_REQUESTED** [review]
@johnyaku  
Looks good!
please add case in the unit test where norm produces zeroes  instead of negatives

**Review by NicoleEO — CHANGES_REQUESTED** [review]
A note, if you are working with multipanel data. We are aware that this function is missing the ability to run on multipanels. As the function stands now, this assumes single panel studies.

**Comment by johnyaku** [comment]
Sorry! I only intended this PR to fix the typo (Codeclass >> CodeClass).
The later changes with `max(difference,0)` were experimental and not yet tested.
I should have created a new branch -- didn't realise that subsequent commits would be added to the PR.

Still, you are welcome to adopt the idea of setting counts to zero if they would have come negative after subtracting background. I'll open another PR if I get it to work in the meantime.

**Comment by NicoleEO** [comment]
@johnyaku, thanks for your valuable input. I am revamping this function here to allow for multipanel data: https://github.com/Nanostring-Biostats/GeomxTools/tree/iss110-bksubtract. Feel free to follow and comment on this revised version while I'm still working on it.

**Pull request closed without merging**
